name: Run Gradle on PRs
on: pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./forge

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Artifct
        uses: actions/upload-artifact@v4
        with:
          name: Mod jars
          path: forge/build/libs/
