name: Generate Python zip
on:
  workflow_dispatch:

jobs:
  python-zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          curl -L -o python.zip https://www.python.org/ftp/python/3.11.7/python-3.11.7-embed-amd64.zip
          mkdir building
          unzip python.zip -d building/python
          mv backend/* building/

      - name: Upload Artifct
        uses: actions/upload-artifact@v4
        with:
          name: python-zip
          path: building/*
