name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./forge

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Release .jar
        run: ./.github/workflows/upload_asset.sh "parmenashp/minecraft-narrator" ./forge/build/libs/*${GITHUB_REF##*/}.jar $GITHUB_TOKEN

  python-zip:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Prepare python zip
        run: |
          curl -L "https://www.python.org/ftp/python/3.11.7/python-3.11.7-embed-amd64.zip" -o python.zip
          mkdir building
          unzip python.zip -d building/python
          curl -L "https://bootstrap.pypa.io/get-pip.py" -o building/python/get-pip.py
          cd building/python
          ./python.exe get-pip.py
          echo "import site" >> ./python311._pth
          mv ../../backend/* ..

      - name: Release Python zip
        run: |
          tar -czf backend.zip building
          ./.github/workflows/upload_asset.sh "parmenashp/minecraft-narrator" backend.zip $GITHUB_TOKEN
